// App base URL for image proxy - imported dynamically in browser context
// This is a fallback value - actual base URL should be determined from request at runtime
export const APP_BASE_URL = process.env.NEXT_PUBLIC_APP_BASE_URL || ''

// List of attributes that were introduced after 1995 and should be removed
export const MODERN_ATTRIBUTES = [
  // Style and class attributes
  'style',
  'class',

  // Accessibility and data attributes
  'aria-',
  'data-',
  'role',
  'itemscope',
  'itemtype',
  'itemprop',
  'accesskey',

  // Resource loading attributes
  'integrity',
  'crossorigin',
  'loading',
  'fetchpriority',
  'decoding',
  'rel',
  'async',
  'defer',
  'nomodule',

  // Modern input/editing attributes
  'contenteditable',
  'spellcheck',
  'autocomplete',
  'autocapitalize',
  'autofocus',
  'enterkeyhint',
  'inputmode',

  // Web components
  'is',
  'nonce',
  'part',
  'slot',
  'translate',

  // JavaScript event handlers - comprehensive list
  'onabort',
  'onafterprint',
  'onanimationend',
  'onanimationiteration',
  'onanimationstart',
  'onbeforeprint',
  'onbeforeunload',
  'onblur',
  'oncanplay',
  'oncanplaythrough',
  'onchange',
  'onclick',
  'oncontextmenu',
  'oncopy',
  'oncut',
  'ondblclick',
  'ondrag',
  'ondragend',
  'ondragenter',
  'ondragleave',
  'ondragover',
  'ondragstart',
  'ondrop',
  'ondurationchange',
  'onemptied',
  'onended',
  'onerror',
  'onfocus',
  'onfocusin',
  'onfocusout',
  'onfullscreenchange',
  'onfullscreenerror',
  'ongotpointercapture',
  'onhashchange',
  'oninput',
  'oninvalid',
  'onkeydown',
  'onkeypress',
  'onkeyup',
  'onlanguagechange',
  'onload',
  'onloadeddata',
  'onloadedmetadata',
  'onloadstart',
  'onlostpointercapture',
  'onmessage',
  'onmessageerror',
  'onmousedown',
  'onmouseenter',
  'onmouseleave',
  'onmousemove',
  'onmouseout',
  'onmouseover',
  'onmouseup',
  'onmousewheel',
  'onoffline',
  'ononline',
  'onpagehide',
  'onpageshow',
  'onpaste',
  'onpause',
  'onplay',
  'onplaying',
  'onpointercancel',
  'onpointerdown',
  'onpointerenter',
  'onpointerleave',
  'onpointermove',
  'onpointerout',
  'onpointerover',
  'onpointerrawupdate',
  'onpointerup',
  'onpopstate',
  'onprogress',
  'onratechange',
  'onrejectionhandled',
  'onreset',
  'onresize',
  'onscroll',
  'onsearch',
  'onseeked',
  'onseeking',
  'onselect',
  'onselectionchange',
  'onselectstart',
  'onshow',
  'onstalled',
  'onstorage',
  'onsubmit',
  'onsuspend',
  'ontimeupdate',
  'ontoggle',
  'ontouchcancel',
  'ontouchend',
  'ontouchmove',
  'ontouchstart',
  'ontransitionend',
  'ontransitionrun',
  'ontransitionstart',
  'onunhandledrejection',
  'onunload',
  'onvolumechange',
  'onwaiting',
  'onwebkitanimationend',
  'onwebkitanimationiteration',
  'onwebkitanimationstart',
  'onwebkittransitionend',
  'onwheel',

  // Modern media and presentation attributes
  'playsinline',
  'autoplay',
  'controls',
  'loop',
  'muted',
  'poster',
  'preload',
  'srcset',
  'sizes',
  'importance',
  'intrinsicsize',
  'referrerpolicy',
  'tabindex',

  // SVG-specific attributes
  'viewbox',
  'preserveaspectratio',
  'xmlns',
  'xmlns:xlink',
  'xlink:href',

  // Obsolete but still modern
  'allowfullscreen',
  'allowpaymentrequest',
  'ping',
  'sandbox',
]

// Selectors for elements that should be removed
export const REMOVE_SELECTORS = [
  // HTML5 semantic tags
  /*
  'article',
  'aside',
  'details',
  'figcaption',
  'figure',
  'footer',
  'header',
  'main',
  'mark',
  'nav',
  'section',
  'summary',
  'time',
  */

  // Media tags
  'audio',
  'canvas',
  'source',
  'track',
  'video',

  // Form tags introduced after HTML 3.2
  'datalist',
  'output',
  'progress',
  'meter',

  // Embedded content
  'embed',
  'iframe',
  'object',
  'param',

  // Other HTML5 elements
  'dialog',
  'menu',
  'menuitem',
  'template',
  'picture',
  'portal',
  'slot',
  'svg',
  'button', // surprisingly from html4.0

  // Style and script
  'style',
  'noscript',

  // Meta information
  'meta',
  'link',

  // Dialog elements and useless elements
  '[role="dialog"]',

  // Inputs not inside forms - they're useless without a form
  'input:not(form input)',
  'textarea:not(form textarea)',
  'select:not(form select)',
  'button:not(form button)',
]
